### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by xyanglu** [bucanero/apollo-saves#102]
- **Game name:** Marvel's Spider-Man [CUSA11995]
- **Title ID:** CUSA11995
-
Here is my 100% completion savegame for Marvel's Spider-Man uploaded for use as a forum resource. I've included the auto, manual, and backup saves.

I got the platinum with this save, it's on Spectacular difficulty and has everything completed (except for some unnecessary goals like hideout combat objectives, extra challenge tokens, benchmarks, audio recordings, and one suit upgrade).
I don't think you can get any story trophies from this save, but you can get all the accumulative ones - i.e. do 75 stealth takedowns, complete all Fisk hideouts etc. by just doing the corresponding task once.

This save was done legit, no cheats. Everything completed on the save includes:

100% Story
28/28 Suits (ESU + Underwear)
24/24 Suit Powers
22/23 Suit Mods
8/8 Gadgets with all upgrades
34/34 Skills
55/55 Backpacks
Level 50+ Superior (1)

[ps4-marvels-spiderman-100-complete-savegame-224282.zip](https://github.com/bucanero/apollo-saves/files/8301573/ps4-marvels-spiderman-100-complete-savegame-224282.zip)

**Comment by xyanglu** [comment]
The reason I'm adding this is because the existing save in the database is for CUSA11993, not CUSA11995. Thanks.

**Comment by bucanero** [comment]
Sorry, this is an encrypted save. The online DB only keeps decrypted saves so they can be used on any firmware.

Feel free to decrypt and re-upload the saves. Just use Apollo to "Export save to .Zip" and then upload the zip file
