### ISSUE TITLE
Using Saves from Online PS4

### ISSUE THREAD

**Issue by The-ELK1** [bucanero/apollo-saves#105]
Hi Buc,

I had a  non JB PS4 on FW8.xx
Before I sold it, I went into Stored Application Data and exported some Game Saves to USB.

I now have a JB 6.72 PS4 (offline)

Ive re-installed the same game/same CUSA with latest game Patch/FW

Is there a way Apollo can re-inject/decrypt the saves to the JB PS4?

**Comment by bucanero** [comment]
you could ask someone using Apollo on a ps4 9.00 jailbreak to import the encrypted saves, and then export them out as decrypted saves.

Once you get the decrypted saves, you should be able to import them on the 6.72 ps4 using Apollo.

Try to find someone with a 9.00 console, or else you'll need to upgrade to 9.00 to import those saves.

**Comment by The-ELK1** [comment]
Thanks.
That worked.
A friend with a PS4 on 9.00 did the decrypt of my saves and sent them back to me.
I imported them back...huge thanks!
