### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by carlosgerlos** [bucanero/apollo-saves#108]
### Game name

Resident evil 5 100%

### Title ID

CUSA04437

### Save description

NOT MINE Credits to "ExileVisionz" on the playsquared foru
[Resident Evil 5 PS4 100%.zip](https://github.com/bucanero/apollo-saves/files/8496985/Resident.Evil.5.PS4.100.zip)
m

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
This is **not** a DECRYPTED save-game. Read the rules before submitting.
