### ISSUE TITLE
[Upload save] Dengeki Bunko Fighting Climax Ignition

### ISSUE THREAD

**Issue by V-Gamer-EX** [bucanero/apollo-saves#110]
### Game name

電撃文庫 FIGHTING CLIMAX IGNITION (1.04)

### Title ID

NPJB00785

### Save description

All Icons/Plates/Titles/Colors/Autographs/MenuCharacters purchased, Ignite Boost maxed out for all Playable/Support characters.
[NPJB00785.zip](https://github.com/bucanero/apollo-saves/files/8567424/NPJB00785.zip)

### FW Version

_HEN_

**Comment by bucanero** [comment]
thanks for sharing 👍
