### ISSUE TITLE
Possible unintended download behavior

### ISSUE THREAD

**Issue by DeltaBlastBurn** [bucanero/apollo-saves#113]
When right-clicking to manually save the zip for a save on a pc, it seems to save a ~200kb html file named 00000001.zip. I'm not sure if this is the intended behavior so I thought I'd mention it

**Comment by bucanero** [comment]
This repository is meant to be used with Apollo, but if you want to browse from your computer, you should use:
- https://bucanero.github.io/apollo-saves/PS4/
- https://bucanero.github.io/apollo-saves/PS3/
