### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by liminha000** [bucanero/apollo-saves#127]
### Game name

Berserk Musou

### Title ID

NPJB00818

### Save description

can make the magic happen in that SAVE DATA?

### Zip link

https://www.mediafire.com/download/ybffu7iipqb19oh

**Comment by bucanero** [comment]
This is only for uploading save games. No place for requests.

**Comment by liminha000** [comment]
sad, I really needed a Save Full of " Berserk Musou PS3 " but since there are no requests, sorry for the inconvenience...😥😅
