### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by StGutem** [bucanero/apollo-saves#13]
- **Game name:** GTA San Andreas
- **Title ID:** NPEB02369
- **Save description:** Platinum Save, only 3 trophys rest (The police, ambulance and firefight missions)
- **Zip file:** [00000001.zip](https://github.com/bucanero/apollo-saves/files/4706083/00000001.zip)

**Comment by bucanero** [comment]
Added in e10e9df745d4b4aa0ab563407d066260369c7b5c
