### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by ajaybnl** [bucanero/apollo-saves#139]
### Game name

Horizon Forbidden West

### Title ID

CUSA24705

### Save description

e.g. Game mostly completed, Legendry Bows acquired.

### Zip link

https://www.mediafire.com/file/23zg2kqw6ef973o/10639842_CUSA24705_AUTOSAVE0.zip/file

### FW Version

9.0

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
thanks for sharing 👍

**Comment by ajaybnl** [comment]
Your welcome. Suggestion: add save to cloud functionality in the apollo save tool.Sent from my iPhoneOn 24-Oct-2022, at 5:49 PM, Damián Parrino ***@***.***> wrote:﻿
thanks for sharing 👍
