### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by StGutem** [bucanero/apollo-saves#14]
- **Game name:** Valiant Hearts: The Great War
- **Title ID:** NPEB01909
- **Save description:** 100% completed, platinum save.
- **Zip file:** [00000002.zip](https://github.com/bucanero/apollo-saves/files/4740960/00000002.zip)

**Comment by bucanero** [comment]
Added in f71ef396c407cbf2a63d4f6e070f3f2d8dd8f996
