### ISSUE TITLE
[Upload save] Kingoms of Amalur fixed

### ISSUE THREAD

**Issue by DeltaBlastBurn** [bucanero/apollo-saves#147]
### Game name

Kingoms of Amalur: Re-Reckoning

### Title ID

CUSA17271 & CUSA17245

### Save description

These are identical saves intended to replace my previous upload. One is for the US release the other for EU. My previous upload is not easily imported to the game. They still require Fatesworn DLC to be used due to equipment effects not in the base game present on most if not all of the custom gear.

Immediately after tutorial. Lots of materials for Blacksmithing and Sagecraft if not-so-OP gear is desired. 4000 max inventory. All OP gear have 100/100 durability (Requires Fatesworn DLC)
[00000001.zip](https://github.com/bucanero/apollo-saves/files/10326926/00000001.zip)

### FW Version

9.0

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by DeltaBlastBurn** [comment]
@bucanero please remove my previous uploads for KOA:RR It is not possible to import them to the game using only Apollo-PS4 1.20, 1.22, or 1.30

**Comment by bucanero** [comment]
> @bucanero please remove my previous uploads for KOA:RR It is not possible to import them to the game using only Apollo-PS4 1.20, 1.22 or 1.30

I have replaced the saves with the new files. 👍

**Comment by DeltaBlastBurn** [comment]
Sorry to necro you but i noticed a few issues.

1. In the replacement save i gave you requires the user to have at least 5
saves and they must import my save to slot 04. If you wouldn't mind
changing the 04 in the folder name to 00 so that the new name
is 10000000_CUSA17271_fmt00svdat00. In doing that users should be able to
start the game and immediately create a save as soon as they gain control
of the pc; they will then be able to close the game and import the modded
save without issue.

2. Just a cosmetic issue that is easily fixable by users. the pc has
corrupted hairstyle. They may notice they're bald in cutscenes and have an
extra shield 3d model in the equipment screen. This can be fixed by
changing the user's hairstyle in any house they come to own. I believe the
earliest house that can be be obtained is by completing the canneroc town
questline and saving the village. They will need to upgrade the house a few
times until they have the mirror available.  Iirc each upgrade costs 1000
gold at zero mercantile score and 980 at max investment (or just wearing
the armor i provided).
