### ISSUE TITLE
[Upload save] It Takes Two CUSA16746

### ISSUE THREAD

**Issue by skar395** [bucanero/apollo-saves#148]
### Game name

It Takes Two

### Title ID

CUSA16746

### Save description

Game completed 100%
[00000001.zip](https://github.com/bucanero/apollo-saves/files/10344527/00000001.zip)

### FW Version

9.0

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
thanks for sharing

**Comment by pankosoknap** [comment]
Inside the zip there is actually a save for CUSA16742. It could be used though by exporting and than importing decrypted data in to CUSA16746 save files.
