### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by kadaaddagmail** [bucanero/apollo-saves#17]
- **Game name:** {Insert _Game Title_}
- **Title ID:** {Insert Title ID, e.g. _BLUS12345_}
- **Save description:** {Insert a description, e.g. _Game completed, everything unlocked!_}
- **Zip file:** (attach or link the `.zip` file)
[00000004.zip](https://github.com/bucanero/apollo-saves/files/5418815/00000004.zip)

**Comment by bucanero** [comment]
Hello @kadaaddagmail 

I see you tried to submit a save, but there's no game name, title or description available.

could you provide the missing information for that file?
