### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by kadaaddagmail** [bucanero/apollo-saves#18]
- **Game name:** {Insert _Game Title_}
- **Title ID:** {Insert Title ID, e.g. _BLUS12345_}
- **Save description:** {Insert a description, e.g. _Game completed, everything unlocked!_}
- **Zip file:** (attach or link the `.zip` file)
[BCES00510]God of War® III
[00000001.zip](https://github.com/bucanero/apollo-saves/files/5418863/00000001.zip)

**Comment by bucanero** [comment]
Hello @kadaaddagmail 

Could you provide a description for this God of War 3 savegame?

could you provide the missing information, thanks
