### ISSUE TITLE
Question PSV format

### ISSUE THREAD

**Issue by Nacheras** [bucanero/apollo-saves#24]
Hi Bucanero!!
Is it possible to add PSV files to the database, such as PS1 or PS2 save games??
If it´s true how can I do it? I have some PS2 saves I´d like to add.
Sorry for my bad English

**Comment by bucanero** [comment]
hello @Nacheras 

for sure! since `.PSV` files are self-contained, open an "issue" on GitHub and upload the .PSV file . Just remember to add the information about the game, title id, description.

no worries about English, si lo prefieres puedes escribir en español también.
saludos

**Comment by Nacheras** [comment]
Muchas gracias por tu respuesta!!
Haré lo que me has dicho, como si de un save data de PS3 se tratara, nombre, ID del juego....
Iré subiendo cuando pueda

**Comment by Nacheras** [comment]
Otra dudilla jejeje, no me deja subir el archivo PSV tal cual, lo tengo que meter dentro de un ZIP??
Es que tu homebrew no me deja crear ZIPs para archivos PSV, entonces pues quería saber si lo creo yo o como se hace desde la aplicación.
Gracias!

**Comment by bucanero** [comment]
> Otra dudilla jejeje, no me deja subir el archivo PSV tal cual, lo tengo que meter dentro de un ZIP??
> Es que tu homebrew no me deja crear ZIPs para archivos PSV, entonces pues quería saber si lo creo yo o como se hace desde la aplicación.
> Gracias!

oh, me habia olvidado que GitHub solo deja subir algunos formatos de archivo.

Si, en el caso del `PSV` lo mas simple es generar un `.zip` en tu PC, solo para "engañar" al Github y subirlo.

**Comment by Nacheras** [comment]
Vale, muchas gracias!! Ya he subido unos cuantos y me ha dejado en formato .zip
Dentro no hay carpeta ni nada, únicamente está el PSV, espero que sea así como había que hacerlo.

**Comment by Nacheras** [comment]
Hubiera sido mejor haberlo subido todo en un mismo archivo y no separarlo en varias secciones verdad?
Si es más trabajoso para ti lo pongo todo en un mismo archivo.

**Comment by bucanero** [comment]
no, un .zip por archivo `.psv` está bien, me sirve para no mezclarlos y tenerlo todo mejor identificado. 

Cuando tenga una oportunidad los empezaré a catalogar en una sección `PS2` para no confundirlo con los de PS3

**Comment by bucanero** [comment]
e6cd299ddfe55a6994420ac68ac799ec5f39255d
