### ISSUE TITLE
[Upload save] Dragon Ball Z: Battle of Z

### ISSUE THREAD

**Issue by Viniciaao** [bucanero/apollo-saves#33]
- **Game name:** Dragon Ball Z: Battle of Z
- **Title ID:** NPUB31322
- **Save description:** All Characters Unlocked, Story Mode Finished, All Game Objects Obtained
- **Zip file:**  [00000002.zip](https://github.com/bucanero/apollo-saves/files/5961793/00000002.zip)

**Comment by bucanero** [comment]
Added in 7c4ed46025d1bfc27b03766648600589d3d5eeae
