### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by ab19981** [bucanero/apollo-saves#360]
### Game name

sikero

### Title ID

CUSA13801

### Save description

e.g. Game completed, everything unlocked! ATTACH ZIP FILE HERE (DRAG & DROP SUPPORTED)

### FW Version

9.0

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by ab19981** [comment]
thn

**Comment by bucanero** [comment]
you must upload a save (ZIP) and add a description.
