### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by Solniz** [bucanero/apollo-saves#372]
### Game name

Dead Or Alive 6

### Title ID

CUSA12153

### Save description

All Costumes, Sunglasses/Acessories, Hairstyles unlocked. 
Note: To see the unlocked DLC characters costumes and hairstyles, you need their respective DLC before.
[CUSA12153.zip](https://github.com/bucanero/apollo-saves/files/12264543/CUSA12153.zip) 

### FW Version

None

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by seisdr** [comment]
This save Is not working
