### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by Opetjahat** [bucanero/apollo-saves#374]
### Game name

Tom clancys wildland

### Title ID

CUSA02819

### Save description

Starter
[Starter_Save_Max_XP-Tier_Resources.zip](https://github.com/bucanero/apollo-saves/files/12472708/Starter_Save_Max_XP-Tier_Resources.zip)

### Zip link

https://www.dropbox.com/s/f80f7emowzljj0l/Starter_Save_Max_XP-Tier_Resources.zip?dl=0

### FW Version

9.0

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
this is not a **DECRYPTED** save.
