### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by Cocome124** [bucanero/apollo-saves#377]
### Game name

P3D

### Title ID

PCSE01274

### Save description

100% complete (costumes, accessories, songs, partners, commu mode) 
[P3D.zip](https://github.com/bucanero/apollo-saves/files/13059332/P3D.zip)

### FW Version

None

### Decrypted saves only

- [x] I confirm the PS Vita save is decrypted.

**Comment by bucanero** [comment]
Sorry, this save is incomplete, you need to export as .ZIP using Apollo, to include all the missing files and folders, like `param.sfo` and other critical files.
