### ISSUE TITLE
(US) Fallout 4 Ultimate Starter Save 

### ISSUE THREAD

**Issue by Flywoodz** [bucanero/apollo-saves#379]
### Game name

Fallout 4

### Title ID

CUSA02557

### Save description

What's included?
Level 420
100,000,000+ caps
255 unspent perk points
Trophies can be unlocked (Including DLC).
Still in vault (Can customize character and perk points).
One of each weapon (Including DLC).
One of each power armor in vault (Including DLC).
999x of each ammo type (Including DLC).
37.000 of each junk type (Including DLC).
999x of each medical supplies type (Including DLC).
All obtainable keys (Including DLC).
All legendary weapons (Including DLC).
All apparel and armor types (Including DLC).
All miscellaneous items (Including DLC).
All map markers show on map
No story side quest or DLC has been 
Save created on `6.72.

### Zip link

https://www.mediafire.com/file/fiilzr95ilo09cs/Fallout_4_Modded_Save_By_Mr.Moan_%2528EU%2529.zip/file

### FW Version

None

### Decrypted saves only

- [ ] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
This is not a **DECRYPTED** save. You must export a .ZIP using Apollo on your PS4 if you want to share a save.

Encrypted saves are not accepted.
