### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by Supe1** [bucanero/apollo-saves#38]
- **Game name:** Max Payne 3
- **Title ID:** BLES 00942 (Europe)
- **Save description:** Game has a few things unlocked not much, save is right before Hard Mode ending, some weapons have been collected, some MP progression inside the save as well
- **Zip file:** 
[maxpayne3eusave.zip](https://github.com/bucanero/apollo-saves/files/6778175/maxpayne3eusave.zip)

**Comment by bucanero** [comment]
Added in 4490ed88c4ca5cf893cee2eae9138c34a7d375ec
