### ISSUE TITLE
Gran Turismo 5 - Cash Bonus, Secret Menu and DLC unlocked

### ISSUE THREAD

**Issue by LordeIlluminati** [bucanero/apollo-saves#39]
- Gran Turismo 5 (2.11 version)
- BCUS98114
- 100.000 Credit bonus, Secret Menu and Downloadable Content Unlocked
- [BCUS98114-GAME.zip](https://github.com/bucanero/apollo-saves/files/6942181/BCUS98114-GAME.zip)

**Comment by bucanero** [comment]
Save added in 119583cb49ee4102bd5c3009df1f9f110b65b407
