### ISSUE TITLE
FC 24 Icons and Heroes Squad

### ISSUE THREAD

**Issue by TylerQuint** [bucanero/apollo-saves#395]
### Game name

FC 24

### Title ID

CUSA 40325,CUSA 40327

### Save description

FC 24 158 Icons and heroes added in free agents.Age has been set 18 so you can use them in career mode
[Icons and heroes ps4.zip](https://github.com/bucanero/apollo-saves/files/13711993/Icons.and.heroes.ps4.zip)

### FW Version

6.72

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
This is not a valid PS4 decrypted save. (missing `sce_sys` folder)
