### ISSUE TITLE
[Upload save] Resident Evil

### ISSUE THREAD

**Issue by Lore11-93** [bucanero/apollo-saves#396]
### Game name

Resident Evil HD Remaster

### Title ID

NPEB020760

### Save description

[NPEB020760.zip](https://github.com/bucanero/apollo-saves/files/13753641/NPEB020760.zip)
EU Save for Only knife trophy (CQC FTW)

### FW Version

None

**Comment by bucanero** [comment]
added in fefeb020d648a3eb1e17a591b7f18de092926ce6
