### ISSUE TITLE
Gran Turismo 6 Starter Bonus

### ISSUE THREAD

**Issue by LordeIlluminati** [bucanero/apollo-saves#40]
- Gran Turismo 6 (1.22 version)
- BCJS37016
- This save file adds 50.000 Credit bonus and the Honda Fit on the start of the campaign to compensate a bit for the lack of Seasonal Events.
- [GT6-BONUSCASH.zip](https://github.com/bucanero/apollo-saves/files/6942193/GT6-BONUSCASH.zip)

**Comment by bucanero** [comment]
Save added in 119583cb49ee4102bd5c3009df1f9f110b65b407
