### ISSUE TITLE
FC6 Save 

### ISSUE THREAD

**Issue by rtinmrpm** [bucanero/apollo-saves#406]
### Game name

Far Cry 6

### Title ID

CUSA15778 

### Save description

Fc6 Story Mode Is Completed All Fnd Captured Just Need 3 Or 4 Check Point And Aircrafts And It's Cusa15778 But In Folder Of CUSA15717 And In The Folder You Must Place This Cusa But In Real It's CUSA15778

### Zip link
https://www.mediafire.com/folder/ebvg2ymlz47r0/CUSA15717

### FW Version

9.0

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
This is not a **DECRYPTED** save. You must export a .ZIP using Apollo on your PS4 if you want to share a save.

Encrypted saves are not accepted.
