### ISSUE TITLE
RDR1

### ISSUE THREAD

**Issue by rtinmrpm** [bucanero/apollo-saves#407]
### Game name

Read Dead Redemption 

### Title ID

CUSA36843 

### Save description

Game completed Just I Done 70% Of Undead Nightmare 

### Zip link

https://www.mediafire.com/folder/q2qtfp0vp2sh6/CUSA36843

### FW Version

9.0

### Decrypted saves only

- [X] I confirm the PS4 save is decrypted.

**Comment by bucanero** [comment]
This is not a DECRYPTED save. You must export a .ZIP using Apollo on your PS4 if you want to share a save.

Encrypted saves are not accepted.
