### ISSUE TITLE
Marvel's Spider-Man: Miles Morales

### ISSUE THREAD

**Issue by Mang0at** [bucanero/apollo-saves#42]
- **Game name:** Marvel's Spider-Man: Miles Morales
- **Title ID:** CUSA17776
- **Save description:** Epilogue Save, Main Story complete, some upgrades
- **Zip file:** (attach or link the `.zip` file)
[00000003.zip](https://github.com/bucanero/apollo-saves/files/7799461/00000003.zip)

**Comment by bucanero** [comment]
thanks for sharing, I'll add it to the list

**Comment by bucanero** [comment]
added in 0278b2b251904d381bba35be618d5ec09f10d192
