### ISSUE TITLE
Shadow of the Colossus

### ISSUE THREAD

**Issue by Mang0at** [bucanero/apollo-saves#43]
- **Game name:** Shadow of the Colossus
- **Title ID:** CUSA08809 
- **Save description:** Game Completed, All Colossi defeated - Easy
- **Zip file:** (attach or link the `.zip` file)
[00000002.zip](https://github.com/bucanero/apollo-saves/files/7799467/00000002.zip)

**Comment by bucanero** [comment]
thanks! 🙏

**Comment by bucanero** [comment]
Added in 0278b2b251904d381bba35be618d5ec09f10d192
