### ISSUE TITLE
Marvel's Spider-Man

### ISSUE THREAD

**Issue by Mang0at** [bucanero/apollo-saves#44]
- **Game name:** Marvel's Spider-Man
- **Title ID:** CUSA11993
- **Save description:** Pax in Bello Save, Medium.  Some Collectibles/optional missions complete.
- **Zip file:** (attach or link the `.zip` file)

**Comment by bucanero** [comment]
hi @Mang0at 

it seems the save file was not attached. Could you re-upload or share a link to the .zip?

**Comment by Mang0at** [comment]
hi @bucanero - my bad, attached now.  Thanks for the tool
[00000004.zip](https://github.com/bucanero/apollo-saves/files/7801266/00000004.zip)
!

**Comment by bucanero** [comment]
added in 0278b2b251904d381bba35be618d5ec09f10d192
