### ISSUE TITLE
[CUSA11456] Ghost of Tsushima

### ISSUE THREAD

**Issue by rajeshca911** [bucanero/apollo-saves#46]
- Ghost of Tsushima
- CUSA11456
-Charm of Fortunate Return x 2
-Charm of Silence
-Charm of Fortune I
-Charm of Fortune II
-Charm of Resolve II
- INFINITE RESOLVE (V 2.07 Only )
-Sarugami Armor (Level V, NG+ ONLY)
[00000003.zip](https://github.com/bucanero/apollo-saves/files/7823280/00000003.zip)

**Comment by bucanero** [comment]
Added in 1355ee60eea24bede56af1025620332b3044d1c6
