### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by rajeshca911** [bucanero/apollo-saves#47]
- **Game name:** SCARLET NEXUS
- **Title ID:** CUSA25132
- **Save description:** Early Game Exploration, Max Kin, Max all  Items, Max Character level
- **Zip file:** 
[00000005.zip](https://github.com/bucanero/apollo-saves/files/7823369/00000005.zip)

**Comment by bucanero** [comment]
Added in 1355ee60eea24bede56af1025620332b3044d1c6
