### ISSUE TITLE
[Days Gone save]

### ISSUE THREAD

**Issue by ChUcHoX4F** [bucanero/apollo-saves#50]
- **Game name:** Days Gone
- **Title ID:** CUSA08966
- **Save description:** Español: Es para el Modo Supervivencia. Desbloquea el trofeo 'Sobrevivir es vivir'. Solo termina el juego. English: It is for Survival Mode. Unlock the 'Surviving is Living' trophy. Just finish the game.
- **Zip file:** [00000001.zip](https://github.com/bucanero/apollo-saves/files/7851206/00000001.zip)

---------------------
- **Game name:** Days Gone
- **Title ID:** CUSA08966
- **Save description:** Español: Es para el Modo Supervivencia. Desbloquea el trofeo 'Days Gone en 60 Segundos'. La partida comienza frente a la horda, con mucha munición. Usa el Chicago Chopper y/o Napal Molotovs para derrotar a la horda. English: It is for Survival Mode. Unlock the 'Days Gone in 60 Seconds' trophy. The game begins in front of the horde, with a lot of ammunition. Use the Chicago Chopper and / or Napal Molotovs to defeat the horde.
- **Zip file:** [00000002.zip](https://github.com/bucanero/apollo-saves/files/7851271/00000002.zip)

**Comment by bucanero** [comment]
added in f8ee2a5f2d9f3e184fea32195390ced4d613ffc0
