### ISSUE TITLE
[Upload save] HOA (CUSA28687)

### ISSUE THREAD

**Issue by subworx** [bucanero/apollo-saves#51]
- **Game name:** HOA (USA)
- **Title ID:** CUSA28687
- **Save description:** 100% Save, all levels unlocked.
- **Zip file:** [00000001.zip](https://github.com/bucanero/apollo-saves/files/7854920/00000001.zip)

**Comment by bucanero** [comment]
added in f8ee2a5f2d9f3e184fea32195390ced4d613ffc0
