### ISSUE TITLE
Grand Theft Auto V

### ISSUE THREAD

**Issue by rajeshca911** [bucanero/apollo-saves#53]
- **Game name:** CUSA00411
- **Title ID:** Grand Theft Auto V
- **Save description:** 100% Save Game, God Mode, Max Everything

- **Zip file:** [00000006.zip](https://github.com/bucanero/apollo-saves/files/7915190/00000006.zip)

**Comment by bucanero** [comment]
added in 37a995a1e841eba37a0a469eabd35702582fb364
