### ISSUE TITLE
DJMAX Respect

### ISSUE THREAD

**Issue by NanospeedGamerYT** [bucanero/apollo-saves#56]
- **Game name:** {DJMAX_Respect}
- **Title ID:** {CUSA08621}
- **Save description:** {Insert a description, e.g. _Game completed, everything unlocked!_}
- **Zip file:** (attach or link the `.zip` file)
[00000001.zip](https://github.com/bucanero/apollo-saves/files/7919159/00000001.zip)

**Comment by bucanero** [comment]
Hola Nano, podrias pasarme una descripcion para el save-game? algo estilo "complete game, all unlocked" asi lo puedo agregar a la lista.

**Comment by bucanero** [comment]
Added in e9d40fa9cb2cc87efbd0c0a598ed229862a0fcb8
