### ISSUE TITLE
 Horizon Chase Turbo CUSA11275

### ISSUE THREAD

**Issue by junaidd007** [bucanero/apollo-saves#59]
- **Game name:** Horizon Chase Turbo
- **Title ID:** CUSA11275
- **Save description:** For the Harder Better, Faster, Stronger trophy all you need to do is finish 3rd in the Pali race in Hawaii. For the completionist trophy all you need to do is get 12000 points, just run in any race and if you haven't, you can get the Finish the last race of the game trophy.
- **Zip file:** [00000001.zip](https://github.com/bucanero/apollo-saves/files/7921654/00000001.zip)

**Comment by bucanero** [comment]
added in 3db77c3f331c3d2a5e3cf291f9a03063e5a60aeb
