### ISSUE TITLE
Gravity Rush 2 [CUSA-04943]

### ISSUE THREAD

**Issue by Solniz** [bucanero/apollo-saves#60]
- **Game name:** Gravity Rush 2
- **Title ID:** CUSA-04943
- **Save description:** 100% completed, all gold challenges, all dusty token items.
- **Zip file:** [[CUSA04943.zip](https://github.com/bucanero/apollo-saves/files/7926952/CUSA04943.zip)]

**Comment by bucanero** [comment]
Added in 3db77c3f331c3d2a5e3cf291f9a03063e5a60aeb
