### ISSUE TITLE
Enhancement: Add game version to savegame information

### ISSUE THREAD

**Issue by subworx** [bucanero/apollo-saves#61]
Hi,

due to jailbroken PS4s have different versions of games floating around and their savegames are possibly not backwards compatible, would it be possible to add a field "(Game) Version" to future savegame uploads and list that in Apollo as well? 
That way I can tell right away if a downloaded save would work with my installed version.

Sorry if this would have better been an "issue" in the Apollo repo directly.

Thanks and regards.

**Comment by bucanero** [comment]
I have updated the upload template so users can add the save-game version info when they share a ps4 save.
