### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by Facu7891** [bucanero/apollo-saves#62]
- **Game name:** {Star Wars Jedi: Fallen Order} {1.11}
- **Title ID:** {CUSA12529}
- **Save description:** {Game Completed, All Planets 100% Explored, All DB Unlocked, All Skins, New Game+, Inquisitor Skin, Red Light Saber}
- **Zip file:** (attach or link the `.zip` file)
[CUSA12529.zip](https://github.com/bucanero/apollo-saves/files/7937592/CUSA12529.zip)

**Comment by bucanero** [comment]
added in 1bab91805e876c586edec53323434eaeee2bd78b
