### ISSUE TITLE
[Upload save] YS IX Monstrum NOX

### ISSUE THREAD

**Issue by remlei** [bucanero/apollo-saves#66]
- **Game name:** YS IX Monstrum NOX v1.00
- **Title ID:** CUSA20414
- **Save description:** 100% complete save file,  LUNATIC★
- **Zip file:** [00000001.zip](https://github.com/bucanero/apollo-saves/files/7968159/00000001.zip)

**Comment by bucanero** [comment]
added in 89c3f592d90bf9eab55ca2506d58c736129003a9
