### ISSUE TITLE
[Upload save] CRYSTAR

### ISSUE THREAD

**Issue by remlei** [bucanero/apollo-saves#67]
- **Game name:** CRYSTAR v1.0
- **Title ID:** CUSA15175
- **Save description:** 100% save file  Rie max level 99 the rest is Level 90+
- **Zip file:** [00000002.zip](https://github.com/bucanero/apollo-saves/files/7968165/00000002.zip)

**Comment by bucanero** [comment]
added in 89c3f592d90bf9eab55ca2506d58c736129003a9
