### ISSUE TITLE
[Upload save] FINAL FANTASY VII

### ISSUE THREAD

**Issue by remlei** [bucanero/apollo-saves#68]
- **Game name:** FINAL FANTASY VII v1.0
- **Title ID:** CUSA01875
- **Save description:** Max level 50 all character, all matera mastered.
- **Zip file:** ([00000003.zip](https://github.com/bucanero/apollo-saves/files/7968174/00000003.zip)

**Comment by bucanero** [comment]
added in 89c3f592d90bf9eab55ca2506d58c736129003a9
