### ISSUE TITLE
[Upload save] YS VIII Lacrimosa of Dana

### ISSUE THREAD

**Issue by remlei** [bucanero/apollo-saves#69]
- **Game name:** YS VIII Lacrimosa of Dana v1.0
- **Title ID:** CUSA08570
- **Save description:** All Character MAX level, all skills unlock and mastered, all weapons upgraded, Laxia 9999Str 4500def, the rest are on 2500 - 3500+STR. Dana Eternia era stats 9999STR. INFINITY-INFERNO mode. 100% save file, 139hours playtime
- **Zip file:**  [00000004.zip](https://github.com/bucanero/apollo-saves/files/7968194/00000004.zip)

**Comment by bucanero** [comment]
added in 89c3f592d90bf9eab55ca2506d58c736129003a9
