### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by florinsdistortedvision** [bucanero/apollo-saves#74]
- **Game name:** {Persona 5 Royal} {1.02}
- **Title ID:** {CUSA17419}
- **Save description:** {Game finished on easy difficulty, no hacks or cheats.}
- **Zip file:** [CUSA17419.zip](https://github.com/bucanero/apollo-saves/files/7993683/CUSA17419.zip)

**Comment by bucanero** [comment]
added in ecff775b69df6c4c21b48fcbc0468ddbd4228ab6
