### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by florinsdistortedvision** [bucanero/apollo-saves#75]
- **Game name:** {Shin Megami Tensei: Persona 3 FES}
- **Title ID:** {SLUS21621}
- **Save description:** {This is a finished save of the PS2toPS4 custom pkg from the undub (tho it doesnt make a difference if the game is undub or not). As long as is the same Title ID, it should work}
- **Zip file:** [SLUS21621.zip](https://github.com/bucanero/apollo-saves/files/7993731/SLUS21621.zip)

**Comment by bucanero** [comment]
I have extracted the original PS2 save and added it here ( a7a17b47257b08b913f52959bfc8eb14bad1790b )

I'll eventually add PS2 memcard management to Apollo PS4 so these saves will be easy to import/export and use it across any system.
