### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by HCK3RINO** [bucanero/apollo-saves#88]
- **Game name:*Need For Speed:Heat*
- **Title ID:*CUSA15090*
- **Save description:*100% Completed save with 1.5M cash [Uploaded By HCK3RINO]*
- **Zip file:*https://www.mediafire.com/file/vji9y0jbi3v0m7m/cusa15090.zip/file*

**Comment by bucanero** [comment]
Sorry, this is an encrypted save. The online DB only keeps decrypted saves so they can be used on any firmware.

Feel free to decrypt and re-upload the saves.
