### ISSUE TITLE
[Upload save]

### ISSUE THREAD

**Issue by Facu7891** [bucanero/apollo-saves#91]
- **Game name:** {Marvel's Spider-man} {1.17}
- **Title ID:** {CUSA11993}
- **Save description:** {Complete Game, All Suits (Including Secret ESU Suit), Gadgets & Skills, 100% Main Game & DLCs}
- **Zip file:** [00000001.zip](https://github.com/bucanero/apollo-saves/files/8055477/00000001.zip)

**Comment by xyanglu** [comment]
This save is compatible for CUSA11995.

Could this be added for CUSA11995 as well?

Thank you
